import { Injectable, Logger } from "@nestjs/common";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { mkdirSync, promises as fs } from "node:fs";
import * as path from "node:path";
import { downloadDisposition, inlineContentType } from "../util/uploads.util";

/** How long a redirect target stays valid. Clients re-request `/uploads/<file>` for a fresh one. */
export const SIGNED_URL_TTL_SECONDS = 60 * 60;

/** Where a served attachment's bytes come from. */
export type StoredFile = { kind: "redirect"; url: string } | { kind: "disk"; path: string };

/**
 * Where card attachment bytes live. With `AWS_S3_BUCKET_NAME` set (Railway
 * bucket wired to the API service — see `DEPLOY.md`) objects go to that
 * S3-compatible bucket; without it they go to `UPLOADS_DIR` on local disk so
 * `pnpm dev` needs no bucket. The container's own disk is never used in
 * production: it is wiped on every Railway deploy.
 *
 * The object key is the stored filename (`buildStoredFilename`), so the
 * `Attachment.filename` column and `/uploads/<file>` URLs are identical in
 * both modes.
 */
@Injectable()
export class AttachmentStorageService {
  private readonly logger = new Logger(AttachmentStorageService.name);
  private readonly bucket = process.env.AWS_S3_BUCKET_NAME;
  private readonly s3: S3Client | null;
  private readonly uploadsDir = process.env.UPLOADS_DIR ?? path.join(process.cwd(), "uploads");

  constructor() {
    if (this.bucket) {
      // Credentials come from AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY via the SDK's default chain.
      // Region is passed explicitly: the JS SDK reads only AWS_REGION, but Railway's preset names it AWS_DEFAULT_REGION.
      this.s3 = new S3Client({
        endpoint: process.env.AWS_ENDPOINT_URL,
        region: process.env.AWS_REGION ?? process.env.AWS_DEFAULT_REGION ?? "auto",
        forcePathStyle: process.env.AWS_S3_FORCE_PATH_STYLE === "true",
      });
      this.logger.log(`Attachments stored in bucket "${this.bucket}"`);
    } else {
      this.s3 = null;
      mkdirSync(this.uploadsDir, { recursive: true });
      this.logger.warn(`AWS_S3_BUCKET_NAME not set — attachments stored on local disk at ${this.uploadsDir}`);
    }
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    if (this.s3) {
      await this.s3.send(new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: body, ContentType: contentType }));
      return;
    }
    await fs.writeFile(this.diskPath(key), body);
  }

  /** Best-effort: a missing object is not an error (the row is what matters). */
  async remove(key: string): Promise<void> {
    try {
      if (this.s3) {
        await this.s3.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
      } else {
        await fs.unlink(this.diskPath(key));
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
        this.logger.warn(`Could not delete attachment object ${key}: ${(err as Error).message}`);
      }
    }
  }

  /**
   * Bucket mode: a short-lived signed GET URL that carries the same response
   * headers `setUploadHeaders` sets on disk — raster images inline, everything
   * else forced to download under its original name. Disk mode: the file path,
   * or `null` if it doesn't exist.
   */
  async resolve(key: string): Promise<StoredFile | null> {
    if (this.s3) {
      const inlineType = inlineContentType(key);
      const command = new GetObjectCommand({
        Bucket: this.bucket,
        Key: key,
        ...(inlineType
          ? { ResponseContentType: inlineType }
          : { ResponseContentDisposition: downloadDisposition(key) }),
      });
      return { kind: "redirect", url: await getSignedUrl(this.s3, command, { expiresIn: SIGNED_URL_TTL_SECONDS }) };
    }
    const filePath = this.diskPath(key);
    const exists = await fs.stat(filePath).then((s) => s.isFile(), () => false);
    return exists ? { kind: "disk", path: filePath } : null;
  }

  private diskPath(key: string): string {
    // Keys are generated by `buildStoredFilename`, but `/uploads/:filename` is public input.
    return path.join(this.uploadsDir, path.basename(key));
  }
}
